mutation UpdateExamType($lastchange: DateTime!, $id: UUID!, $master_exam_type_id: UUID, $name: String, $name_en: String, $min_score: Float, $max_score: Float, $min_required_score: Float, $data: String, $duration: Int,) {
  examTypeUpdate(
    examType: {
      lastchange: $lastchange
      id: $id
      masterExamTypeId: $master_exam_type_id
      name: $name
      nameEn: $name_en
      minScore: $min_score
      maxScore: $max_score
      minRequiredScore: $min_required_score
      data: $data
      duration: $duration
    }
  ) {
    __typename
    ...Error
    ...ExamType
  }
}

fragment Error on ExamTypeGQLModelUpdateError {
  msg
  input
  failed
  Entity
  {
    lastchange
  }
}

fragment ExamType on ExamTypeGQLModel{
  lastchange
  id
  masterExamTypeId
  name
  nameEn
  minScore
  maxScore
  minRequiredScore
  data
  duration
  admissionId
}