query {
  result: admissionPage {
    __typename
    ...Admission
  }
}

fragment Admission on AdmissionGQLModel {
  id
  lastchange
  name  
  nameEn
  programId
  applicationStartDate
  applicationLastDate
  endDate
  conditionDate
  requestConditionStartDate
  requestConditionLastDate
  requestExamStartDate
  requestExamLastDate
  paymentDate
  requestEnrollmentStartDate
  requestEnrollmentEndDate
  created
  createdbyId
  createdby{
    id
  }
  changedbyId
  changedby{
    id
  }
  rbacobjectId
  rbacobject{
    id
  }
}