query ReadPayment($id: UUID!) {
  result: paymentById(id: $id) {
    __typename
    ...Payment
  }
}

fragment Payment on PaymentGQLModel{
  lastchange
  paymentInfoId
  id
  bankUniqueData
  variableSymbol
  amount
  created
  createdbyId
  createdby{
    id
  }
  changedbyId
  changedby{
    id
  }
  rbacobjectId
  rbacobject{
    id
  }
}