query{
  result: studentAdmissionPage {
    __typename
    ...StudentAdmission
  }
}

fragment StudentAdmission on StudentAdmissionGQLModel{
  lastchange
  id
  admissionId
  studentId
  stateId
  extendedConditionDate
  admissioned
  enrollmentDate
  created
  createdbyId
  createdby{
    id
  }
  changedbyId
  changedby{
    id
  }
  rbacobjectId
  rbacobject{
    id
  }
}